"""initial migration

Revision ID: 3dee83604016
Revises: 
Create Date: 2024-12-11 11:50:55.643029

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3dee83604016"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heroes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("powers", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_heroes_alias"), "heroes", ["alias"], unique=True)
    op.create_index(op.f("ix_heroes_id"), "heroes", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_heroes_id"), table_name="heroes")
    op.drop_index(op.f("ix_heroes_alias"), table_name="heroes")
    op.drop_table("heroes")
    # ### end Alembic commands ###
